title: "Services — Darlington"

vehicle_sizes:
  - id: car
    label: Car
    price_delta: 0
    time_delta_min: 0
  - id: suv
    label: SUV / MPV
    price_delta: 10
    time_delta_min: 25
  - id: van
    label: Van (SWB)
    price_delta: 25
    time_delta_min: 40

valeting:
  tiers:
    - id: mini
      name: "Mini Valet (maintenance)"
      duration_min: 60
      prices: { car: 35, suv: 45, van: 55 }
      includes:
        - Pre-wash + two-bucket hand wash
        - Wheels cleaned; tyres dressed; dry & door shuts
        - Light interior vacuum (seats, mats, boot)
        - Wipe plastics; interior & exterior glass
      excludes:
        - Shampoo/extraction
        - Paint decontamination or polishing
        - Leather treatment
        - Engine bay detail
    - id: full
      name: "Full Valet (standard)"
      duration_min: 150
      prices: { car: 65, suv: 80, van: 95 }
      includes:
        - Everything in Mini
        - Full interior vac incl. under mats & boot
        - Plastics cleaned & dressed; deodorise
        - Exterior tar-spot removal; door sills
        - Entry-level wax/sealant
      excludes:
        - Machine polishing
        - Upholstery extraction on all seats (unless added)
        - Ceramic coatings
    - id: deep
      name: "Deep Clean (premium)"
      duration_min: 240
      prices: { car: 120, suv: 145, van: 170 }
      includes:
        - Everything in Full
        - Fabric shampoo/extraction (seats, carpets, mats)
        - Leather clean & condition (if applicable)
        - Headliner spot clean; deodorise
        - Iron fallout removal + clay bar
        - Single-stage gloss polish
        - High-grade wax/sealant
        - Engine bay clean
  focused:
    - id: interior_reset
      name: "Interior Reset"
      duration_min: 165
      prices: { car: 85, suv: 100, van: 115 }
      includes:
        - Full vac; plastics deep clean & dress
        - Fabric shampoo/extraction
        - Leather clean & condition (if applicable)
        - Glass; deodorise
    - id: exterior_enhance
      name: "Exterior Enhancement"
      duration_min: 150
      prices: { car: 95, suv: 115, van: 135 }
      includes:
        - Pre-wash, wash, wheels, tyres
        - Tar + iron removal; clay bar
        - Hand/DA gloss polish
        - Paint sealant; exterior glass

machine_polish:
  stages:
    - id: enhancement
      name: "Single-Stage Enhancement"
      duration_min: 300
      prep_required: "Exterior Enhancement or Deep Clean"
      prices: { car: 180, suv: 210, van: 240 }
      includes:
        - Paint decontamination (tar, iron, clay)
        - Single-stage machine polish (gloss focus)
        - Panel wipe and sealant
      excludes:
        - Heavy defect removal; wetsanding; ceramic coating
    - id: correction_2
      name: "Two-Stage Correction"
      duration_min: 420
      prep_required: "Exterior Enhancement or Deep Clean"
      prices: { car: 320, suv: 370, van: 420 }
      includes:
        - Cut + refine machine polish
        - Panel wipe; high-grade sealant
      excludes:
        - Ceramic coating

ceramic:
  coatings:
    - id: ceramic_12m
      name: "Ceramic Coating — 12 months"
      duration_min: 360
      prep_required: "Single-Stage Enhancement minimum"
      prices_from: { car: 260, suv: 300, van: 340 }
      includes:
        - Full decon + machine polish (single-stage)
        - Ceramic coating on paintwork (rated ~12 months)
        - Glass cleaned; tyres dressed; trims treated
      notes:
        - Cure time guidance provided; no wash 7 days
    - id: ceramic_24m
      name: "Ceramic Coating — 24 months"
      duration_min: 420
      prep_required: "Two-Stage Correction recommended"
      prices_from: { car: 420, suv: 480, van: 540 }
      includes:
        - Full decon + two-stage correction
        - 2-year ceramic on paint; wheel faces sealed
        - Glass rain repellent on screen

add_ons:
  - { id: pet_hair, name: "Pet hair removal", price: "£20–£40" }
  - { id: ozone, name: "Ozone odour treatment", price: "£25" }
  - { id: fabric_protect, name: "Fabric protector (Scotchgard)", price: "£25 car / £35 SUV–van" }
  - { id: leather_care, name: "Leather deep clean + condition", price: "£20–£30" }
  - { id: headlights, name: "Headlight restoration (pair)", price: "£30" }
  - { id: engine_bay, name: "Engine bay detail", price: "£20" }
  - { id: hard_wax, name: "Hard wax upgrade", price: "£15" }
  - { id: ceramic_lite, name: "Ceramic-lite sealant (≈12 months)", price: "+£60" }
  - { id: wheel_seal, name: "Wheel face sealant", price: "£20" }
  - { id: roof, name: "Convertible roof clean + seal", price: "£40–£60" }
